Update SmsMethodCallHandler.kt
Quick fix to the following error coming out of nowhere:

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=200, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {MainActivity}: java.lang.IllegalStateException: Reply already submitted
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5230)
 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5271)
 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:237)
 	at android.app.ActivityThread.main(ActivityThread.java:7948)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
 Caused by: java.lang.IllegalStateException: Reply already submitted
 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.execute(SmsMethodCallHandler.kt:162)
 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onRequestPermissionsResult(SmsMethodCallHandler.kt:357)
 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:640)
 	at MainActivity.onRequestPermissionsResult(MainActivity.kt:34)
 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8474)
 	at android.app.Activity.dispatchActivityResult(Activity.java:8296)
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5223)